Update error handling
Recognize "Cannot" in addition to "Unable". Also change repeated if
statements to elif and make spacing more consistent.

diff --git a/urreg b/urreg
--- a/urreg
+++ b/urreg
@@ -390,15 +390,16 @@ add_course()
 
         if printf "%s\n" "$html" | grep -qF "Permission required"; then
             log 'add_course(): Error: permission code required'
-
             echo 'Error: permission code required.' >&2
             exit 1
-        fi
-
-        if printf "%s\n" "$html" | grep -qF "Unable"; then
+        elif printf "%s\n" "$html" | grep -qF "Unable"; then
             log 'add_course(): Error: unable to register'
             echo 'Error: unable to add course (yet).' >&2
-            add_course "$@"
+            add_course "$@" || exit 1
+        elif printf "%s\n" "$html" | grep -qF "Cannot"; then
+            log 'add_course(): Error: cannot register at this time'
+            echo 'Error: cannot register at this time.' >&2
+            exit 1
         fi
     ) || {
         echo 'Error: unable to add course.' >&2
