Add error checking to add_course + minor changes
Seems to introduce a bug where it won't actually register for the
given courses.

diff --git a/urreg b/urreg
--- a/urreg
+++ b/urreg
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 LOGFILE="LOG"
-CONFIRM_CRN=:
+CONFIRM_CRN=
 
 > $LOGFILE
 
@@ -61,9 +61,9 @@ parse_netrc()
 
 	if is_insecure $netrc
 	then
-        log 'parse_netrc(): netrc is insecure'
-
 		echo 'Warning: .netrc has insecure permissions.' >&2
+
+        log 'parse_netrc(): netrc is insecure'
 
         log 'parse_netrc(): asking to fix netrc security'
         read -p 'Do you want to fix it? [Y/n] ' fix
@@ -204,10 +204,17 @@ read_crn()
                 break
             fi
 
-            log 'read_crn(): invalid crn entered; looping'
-
             echo 'Error: invalid CRN.' >&2
+
+            log 'read_crn(): invalid crn entered; looping'
         done
+
+        if ! [ $CONFIRM_CRN ]
+        then
+            log 'read_crn(): skipping crn confirmation'
+
+            return 0
+        fi
 
         log "read_crn(): \$crn_confirm = $crn_confirm; reading crn"\
             "confirmation"
@@ -224,9 +231,9 @@ read_crn()
             return 0
         fi
 
-        log "read_crn(): CRNs $crn and $crn_confirm do not match; looping"
-
         echo 'Error: CRNs do not match.' >&2
+
+        log "read_crn(): CRNs $crn and $crn_confirm do not match; looping"
     done
 
     log 'read_crn(): Error: reached unreachable statement.'
@@ -245,9 +252,9 @@ read_crns()
 
     if [ -z $crns ]
     then
-        log 'read_crns(): \$crns is empty; not registering for any classes'
-
         echo 'Warning: you have not entered any classes to register for.' &>2
+
+        log 'read_crns(): \$crns is empty; not registering for any classes'
 
         log 'read_crns(): END'
 
@@ -263,12 +270,13 @@ add_course()
 {
     log 'add_course(): BEGIN'
 
-    crn=$1
-    ts=$2
+    crn="$1"
+    ts="$2"
 
     log "add_course(): using \$crn = $crn, \$ts = $ts"
 
-    if [ "$3" = 'A' ] || [ "$3" = 'N' ]
+    # 'A' is for auditing; 'N' is for normal grading
+    if [ "$3" = 'A' ]
     then
         gt="$3"
 
@@ -279,11 +287,62 @@ add_course()
         log "add_course(): grade type not given; \$gt = $gt"
     fi
 
-    curl -k --ssl "https://webreg.its.rochester.edu/prod/tapp?Navigate=regdisplay1.jsp&OnError=error.jsp&TS=$ts&SHOP_CART=true&LOAD_SCHEDULE=false&ADD_CALL_NUM=$crn&GRADE_TYPE=$gt"
+    add_url="https://webreg.its.rochester.edu/prod/tapp?Navigate=regdisplay1.jsp&OnError=error.jsp&TS=$ts&SHOP_CART=true&LOAD_SCHEDULE=false&ADD_CALL_NUM=$crn&GRADE_TYPE=$gt"
 
-    curl -k --ssl "https://webreg.its.rochester.edu/prod/tapp?Navigate=CartResults.jsp&OnError=error.jsp&TS=$ts&SUBMIT_CART=true&WAITPAGE=PleaseWait.htm"
+    submit_url="https://webreg.its.rochester.edu/prod/tapp?Navigate=CartResults.jsp&OnError=error.jsp&TS=$ts&SUBMIT_CART=true&WAITPAGE=PleaseWait.htm"
+
+    log "add_course(): adding course to cart using \$add_url = $add_url"
+
+    # I'm not sure why but for both curl and Ruby's Mechanize, but not for
+    # browsers, the SSL certificate for the registration pages is found invalid
+    # and can't be validated properly. It works with the check disabled but is
+    # less secure.
+
+    add_html=$(curl -s -k --sslv3 "$add_url")
+    err=$?
+
+    if [ $err != 0 ]
+    then
+        echo 'Error: curl request failed.' >&2
+
+        log "add_course(): curl request failed; exit code = $err"
+
+        log 'add_course(): END'
+
+        return 1
+    fi
+
+    # TODO - analyze add_html for errors
+
+    echo "$add_html"
+
+    log 'add_course(): added course to cart'
+
+    log "add_course(): submitting cart using \$submit_url = $submit_url"
+
+    submit_html=$(curl -s -k --sslv3 "$submit_url")
+    err=$?
+
+    if [ $err != 0 ]
+    then
+        echo 'Error: curl request failed.' >&2
+
+        log "add_course(): curl request failed; exit code = $err"
+
+        log 'add_course(): END'
+
+        return 1
+    fi
+
+    # TODO - analyze submit_html for errors
+
+    echo "$submit_html"
+
+    log 'add_course(): submitted cart'
 
     log 'add_course(): END'
+
+    return 0
 }
 
 if ! read_crns
